version: "3.8"

services:
  bascula:
    build: .
    ports:
      - "${BASCULA_PORT:-8085}:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.bascula-web.rule=Host(`bascula.rsagents.cloud`)
      - traefik.http.routers.bascula-web.entrypoints=web
      - traefik.http.routers.bascula-web.middlewares=redirect-to-https@file
      - traefik.http.routers.bascula-secure.rule=Host(`bascula.rsagents.cloud`)
      - traefik.http.routers.bascula-secure.entrypoints=websecure
      - traefik.http.routers.bascula-secure.tls.certresolver=letsencrypt
      - traefik.http.services.bascula.loadbalancer.server.port=80
    restart: unless-stopped
